In [1]:
# 1
import numpy  as np

In [2]:
# 2
a = np.zeros (10)
print (a)
# 3
a = np.ones (10)
print (a)
# 4
a = a*5
print (a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [3]:
# 5
b = np.arange (10,51)
print (b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [4]:
# 6
c = np.arange (10,51,2)
print (c)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [5]:
# 7
m = np.arange (0,9)
m = m.reshape (3,3)
print (m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
# 8
m = np.zeros (9)
m = m.reshape (3,3)
for i in range (3):
    for j in range (4):
        if i ==j:
            m[i, j] = 1.0
print (m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
# 9
r = np.random.rand(1)
print(r)

[0.87879867]


In [8]:
# 10
ra = np.random.normal(1, 100, 25)
print (ra)

[ 147.20764447   95.88478306  105.42991104   14.8257749    46.60217618
   63.03332606  -74.50851828 -188.9312619    32.26850162 -210.26492418
  -46.39162297   56.21063345 -164.84765807  -18.2993992   -80.31989926
   54.33720207  -49.20885232  -70.88247381  -32.06359875  163.2937433
  -35.75249163   13.85135316 -149.85537031  -76.27904124   61.9459786 ]


In [9]:
# 11
a = np.arange (0.01, 1.01, 0.01)
a = a.reshape (10,10)
print (a)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [10]:
# 12
a = np.linspace (0, 1, 20)
print (a)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [11]:
# 13
mat = np.arange(1,26).reshape(5,5)
print (mat)
print (mat[2:,1:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [12]:
# 14
print (mat[3,4:])

[20]


In [13]:
# 15
print (mat[:3, [1]])

[[ 2]
 [ 7]
 [12]]


In [14]:
# 16
print (mat[-1,:])

[21 22 23 24 25]


In [15]:
# 17
print (mat[-2:,:])

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [16]:
# 18
print(mat.sum())

325


In [17]:
# 19
print(mat.std())

7.211102550927978


In [18]:
# 20
answer = np.arange(5)
for i in range (5):
    answer [i] = mat[:, i].sum()
print (answer)

[55 60 65 70 75]
